---
- name: deployment ELK agent.
  hosts: all
  gather_facts: false
  tasks:

    - name: Create dir
      win_file:
          path: 'C:\Program Files\ELK'
          state: directory

    - name: Import windows agent # Télécharge l'agent décompressé depuis l'ordinateur lançant le playbook
      ansible.builtin.win_copy:
        src: ../../../../elastic-agent-8.9.0-windows-x86_64 # récupération de l'agent hors du répo Git
        dest: 'C:\Program Files\ELK\elastic-agent-8.9.0-windows-x86_64'

    - name: Deployment agent # utilise -f pour accepter l'installation (Force) et --insecure pour passer les certificats
      win_shell: |
        cd 'C:\Program Files\ELK\elastic-agent-8.9.0-windows-x86_64'
        .\elastic-agent.exe install --url=https://10.202.0.174:8220/ --enrollment-token=VVAwR1FJd0JrY1h4dmpEQlY3eTI6RVk1VWdVZ3JRcHliR1ZoRkpTQ0xkZw== -f --insecure 