---

- name: Install sysmon
  hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:

    - name: Register Microsoft key 
      ansible.builtin.shell: |  
        wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb

    - name: Install sysmon
      ansible.builtin.apt:
        name: sysmonforlinux
        force: yes
        state: present

    - name : Create sysmon dir
      file:
        path: /home/test/sysmon
        state: directory

    - name: Get sysmon XML
      ansible.builtin.copy:
        src: ./files/sysmon-xml.xml
        dest: /home/test/sysmon/sysmon-xml.xml
        owner: test
        group: test
        mode: '0555'

    - name: Charge sysmon file 
      ansible.builtin.shell: |
        sysmon -i /home/test/sysmon/sysmon-xml.xml
        sudo tail -f /var/log/syslog | sudo /opt/sysmon/sysmonLogView