# cloud-config.yaml
# Cloud-init configuration file
users:
  - name: elk
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6JL0UZRb1/AKCBE6zRK3GGGfkTJZWzPhx55vmdqMZTc42fs3ajyC53jiJiMY2SEWxjKohkCEuFzluB7zbJvSp2A6veFoTjoETetad2wv8GwsexR67x2RQn+MdIB2w0OhvUN3Nsx33alyEQ4GD1Q1EKfXyVCH91X52/FCPF6mMhDJtzoBOaKfRJfXJsjoNNWQuuKFsL0iKQdMPTzVvfafi1XE0zIfSTR4ZjORIAvjmMVNbukl6tEDrsiTBveXiVMHsY7D0GhGhZXH2FstMzQ5dhRC/qnWjTKzb16yD2xO4DGxvY9xxuJI6Qu/HO/Sq1Ymv0K1qizKuzBWgAxGlVZ5mL/5qWeRK2kKt7HnA/lmuP2HvHYTnbGs3+Z0k3FRBQcahxIzQNYRuNfE0YZbXL+uhYbL+CphaxUUBCYD5ndyXEbdjL0+eL75BxopdhB70HRJJ9T4lgdRl2El1dmRmToQdogqTLQS+OCXN3NFbG1KunWylgLt2TlXbt9JJz2HBzUllmv/x2F7BKIuLUqrLjiIjq384In6oZjZj2cby/LR4HKcLZ7LKrsGT+z6IsjvVHDKfuxwsciENn4N+FYFW13qUV8RBxcz+Lciz4WfSVXhNq+wywvq8AJ4EeJ3IH6WLQzaYDl348ntWpt673Cf9olD5VB4vGh/YId1oqF0rhIPOhw== aksel@RedArch
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

hostname: elk-server

# Additional configurations can be added as needed
