VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ELK-Server" do |db|
  
    db.vm.box = "generic/ubuntu1804"
    db.vm.hostname = "elk-vagrant-server"
    db.vm.network "public_network"
  
    db.vm.provision "shell", inline: <<-SHELL
    
      sudo timedatectl set-timezone Europe/Paris
      sudo apt update
    ##################
    # Install docker #
    ##################
    wget https://get.docker.com/ -O script.sh
    chmod +x script.sh
    ./script.sh
    sudo usermod -aG docker $USER
    ##################
    # Install base   #
    ##################
    sudo apt install -yq git make jq
    git clone https://github.com/pushou/siem.git
    cd siem/
    make es
    make siem
    make fleet
    docker ps -a
    cat secrets/passwords.txt 
    SHELL
  end
end 